# Generated by Django 5.1.7 on 2025-03-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_field', models.BooleanField(default=False)),
                ('int_field', models.IntegerField(default=0)),
            ],
        ),
    ]
