# Generated by Django 5.1.7 on 2025-03-27 22:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_random_code', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='randomcode',
            options={'verbose_name': 'Випадковий код', 'verbose_name_plural': 'Випадкові коди'},
        ),
        migrations.AddField(
            model_name='randomcode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
        migrations.AddField(
            model_name='randomcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AddField(
            model_name='randomcode',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Ім'я користувача"),
        ),
        migrations.AlterField(
            model_name='randomcode',
            name='bool_field',
            field=models.BooleanField(default=False, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='randomcode',
            name='int_field',
            field=models.IntegerField(default=0, verbose_name='Код'),
        ),
    ]
